### ISSUE TITLE
Typo needs to be fixed for Saul quote. Update query provided.

### ISSUE THREAD

**Issue by 716green** [timbiles/Breaking-Bad--API#19]
**Typo in DB**
```
        "quote_id": 81,
        "quote": "You tow suck at peddling meth.",
        "author": "Saul Goodman",
        "series": "Breaking Bad"
```

"quote": "You **_tow_** suck at peddling meth.",

---
The fix is
`
UPDATE quotes SET quote = "You two suck at peddling meth." WHERE quote_id = 81;
`
I'd update it if I had access but I don't. Hope this helps

**Comment by timbiles** [comment]
@716green Should be updated. Thanks for bring that to my attention!
