### ISSUE TITLE
/characters name & limit queries not working

### ISSUE THREAD

**Issue by ahmedbeheiry** [timbiles/Breaking-Bad--API#21]
Hello,
Why can't I combine between name & limit queries in /api/characters

If I tried this:
`/api/characters?name=s&limit=2`
**What I expect:**
A list of 2 characters.
**What I get:**
A list of 17 characters

**Comment by timbiles** [comment]
> Hello,
> Why can't I combine between name & limit queries in /api/characters
> 
> If I tried this:
> `/api/characters?name=s&limit=2`
> **What I expect:**
> A list of 2 characters.
> **What I get:**
> A list of 17 characters

@ahmedbeheiry great catch! I'll push up a change to add that functionality.

**Comment by timbiles** [comment]
@ahmedbeheiry Should be functioning now. Thanks for bringing this to my attention!

https://breakingbadapi.com/api/characters?name=s&limit=2

**Comment by ahmedbeheiry** [comment]
@timbiles 
Thanks for your fast response
