### ISSUE TITLE
Random character endpoint returns empty object

### ISSUE THREAD

**Issue by 90zlaya** [timbiles/Breaking-Bad--API#31]
When trying to fetch random character from [https://www.breakingbadapi.com/api/character/random](url) from time-to time I get empty object as a result instead of array with one Character. I assume that function for fetching Character returns random number which doesn't exist as char_id or # in list of characters.

**Comment by timbiles** [comment]
@90zlaya Thanks for bringing this issue to my attention! The issue was dealing with the Better Call Saul characters. 

https://github.com/timbiles/Breaking-Bad--API/pull/32
