### ISSUE TITLE
Return page name attribute in character object

### ISSUE THREAD

**Issue by 90zlaya** [timbiles/Breaking-Bad--API#33]
Is it possible to return character object with page name attribute included? 

Situation: I've created page to display character details. Let's say it's Walter White. URL to this page would be `base_url/1`. When this page is visited, I would use `/1` to identify that ID of the character details is 1 and then query character details endpoint. Instead of this robust and SEO unfriendly approach, it would be much nicer if URL would be `base_url/walter-white`. I would use `walter-white` to do the query for character details and get the results. 

The only way I could do this now is to manually create mapping between char_id & page_name. When `base_url/walter-white` is visited, I contact this mapping to get char_id and then do the query to the character details endpoint. 

Attribute page_name would be character name with spaces replaced with `-` and dots and all other special characters removed, instead of `&` which would be converted to `-and-`.

**Comment by timbiles** [comment]
> Is it possible to return character object with page name attribute included?
> 
> Situation: I've created page to display character details. Let's say it's Walter White. URL to this page would be `base_url/1`. When this page is visited, I would use `/1` to identify that ID of the character details is 1 and then query character details endpoint. Instead of this robust and SEO unfriendly approach, it would be much nicer if URL would be `base_url/walter-white`. I would use `walter-white` to do the query for character details and get the results.
> 
> The only way I could do this now is to manually create mapping between char_id & page_name. When `base_url/walter-white` is visited, I contact this mapping to get char_id and then do the query to the character details endpoint.
> 
> Attribute page_name would be character name with spaces replaced with `-` and dots and all other special characters removed, instead of `&` which would be converted to `-and-`.

Do you mind clarifying a little more what you are trying to accomplish? It's sounds to me like you are trying to query a character by name, which is currently possible. Try `https://www.breakingbadapi.com/api/characters?name=walter+white`. Is this what you are refering to?

**Comment by 90zlaya** [comment]
@timbiles 

Basically it would be nice to have `page_name` attribute for character like in the example bellow (added after `char_id`): 

```json
[
    {
        "char_id": 1,
        "page_name": "walter-white",
        "name": "Walter White",
        "birthday": "09-07-1958",
        "occupation": [
            "High School Chemistry Teacher",
            "Meth King Pin"
        ],
        "img": "https://images.amcnetworks.com/amc.com/wp-content/uploads/2015/04/cast_bb_700x1000_walter-white-lg.jpg",
        "status": "Presumed dead",
        "nickname": "Heisenberg",
        "appearance": [
            1,
            2,
            3,
            4,
            5
        ],
        "portrayed": "Bryan Cranston",
        "category": "Breaking Bad",
        "better_call_saul_appearance": []
    }
]
```

It would be cool to have this attribute in payload to use as part of URL when creating character details page.

**Comment by timbiles** [comment]
@90zlaya 

That's identical to the name attribute that is already brought in. You could do something like `name.toLowerCase().replace(/ /g, '-')` to create the name in the way you are looking for.

Or if you would like, you can create a pull request adding this attribute to the characters response on the desired endpoint.

**Comment by 90zlaya** [comment]
@timbiles Already solved it in my front-end app but I will try to make PR to make it easier for others. 

Thanks 😊
