### ISSUE TITLE
Mike last name on Breaking Bad S03E13 has a typo

### ISSUE THREAD

**Issue by nunorafaelrocha** [timbiles/Breaking-Bad--API#39]
There's a typo on Mike Ehrmantraut's name on Breaking Bad Season 2, Episode 13.

**Mike Erhmantraut** is incorrect => **Mike Ehrmantraut** is correct

![image](https://user-images.githubusercontent.com/1175149/100237766-a699d580-2f2f-11eb-8e29-4e0003e935ac.png)

**Comment by timbiles** [comment]
Thanks for letting me know! Should be updated now.
