### ISSUE TITLE
Episodes contain an empty string in the list of characters

### ISSUE THREAD

**Issue by nunorafaelrocha** [timbiles/Breaking-Bad--API#40]
Two episodes of the Breaking Bad series contain an empty string in the list of characters.

episode_ids: 38, 46

![image](https://user-images.githubusercontent.com/1175149/100238411-73a41180-2f30-11eb-8c4f-36961f71ef5f.png)

![image](https://user-images.githubusercontent.com/1175149/100238439-7c94e300-2f30-11eb-9940-44b86badcb6f.png)

**Comment by timbiles** [comment]
This should be taken care of as well. Thanks, again!
