### ISSUE TITLE
No image for Holly White

### ISSUE THREAD

**Issue by vvaleri** [timbiles/Breaking-Bad--API#41]
Hello.
Link id 39: https://static.wikia.nocookie.net/breakingbad/images/7/78/Holly.JPG/revision/latest/scale-to-width-down/683?cb=20100413115129

instead image

![holly](https://user-images.githubusercontent.com/66499128/101525920-074bf800-399d-11eb-854c-8e33d6eb9269.png)

**Comment by 90zlaya** [comment]
I've noticed this one too. There was image of an baby previously. Maybe it's better to remove image completely so that default image could kick in?

**Comment by vvaleri** [comment]
I'm not sure I know how can I do that. But I'll figure it out. I just need output all characters on page at once.

**Comment by 90zlaya** [comment]
> I'm not sure I know how can I do that. But I'll figure it out. I just need output all characters on page at once.

This is valid image returned in response and could be found and downloaded which means it will be displayed as image for Holly White. There are two options how to fix this:
1. URL should be updated in database
2. URL should be blacklisted in app and/or replaced with default character image/Holly White image. 

But second option seems like hacking so I would go with the first one.

**Comment by timbiles** [comment]
@vvaleri Should be taken care of now. That image has been replaced with one that is not broken.

**Comment by Mridul2820** [comment]
> @vvaleri Should be taken care of now. That image has been replaced with one that is not broken.

The image link is not working still
