### ISSUE TITLE
Duplicated IDs for Stacey Ehrmantraut

### ISSUE THREAD

**Issue by 90zlaya** [timbiles/Breaking-Bad--API#43]
I've noticed that it's possible to get character details for Stacey Ehrmantraut both on `/characters/55` & `/characters/117`. Second one should be removed. Also, `appearance` node is null on that ID and this might produce bug for anyone using this node and expecting it to always be array.

**Comment by timbiles** [comment]
@90zlaya should be updated. `/characters/55` should be the only instance of Stacey Ehrmantraut. Thanks for bringing this to my attention!
