### ISSUE TITLE
Characters not ordered properly for Breaking Bad category

### ISSUE THREAD

**Issue by 90zlaya** [timbiles/Breaking-Bad--API#44]
Characters not ordered properly on `/characters` enpoint when `/characters?category=Breaking+Bad` added. I would expect to see characters in the same order as before adding `category` param, which is sort by character id in ascending order.

**Comment by timbiles** [comment]
https://github.com/timbiles/Breaking-Bad--API/pull/50

@90zlaya those category endpoints should be ordered correctly now by `char_id`.
