### ISSUE TITLE
Episode with "episode_id": "7" has the value of property "season": " 1" instead of "1".

### ISSUE THREAD

**Issue by edustef** [timbiles/Breaking-Bad--API#46]
Found out the value of property season of episode_id: 7 has a space in front of it. Found this out when I tried to group episodes by id and it was grouped alone in a " 1" key. I fixed it with a trim() but still letting you know.

![image](https://user-images.githubusercontent.com/30721277/106023579-35110b80-60c7-11eb-9329-eadff1305a89.png)

**Comment by timbiles** [comment]
@edustef  Wow, great catch! I'll make that change now.
