### ISSUE TITLE
Characters of Better Call Saul Returning "null" in "appearance" Property

### ISSUE THREAD

**Issue by pandeypiyush94** [timbiles/Breaking-Bad--API#47]
Characters of `Better Call Saul` who hasn't worked in `Breaking Bad` returning `null` in `appearance` Property which sometimes leading to `Null Pointer Exception`. Better to return `0` instead of `null`... :slightly_smiling_face:

![Capture](https://user-images.githubusercontent.com/8748245/106346976-cdcea380-62e0-11eb-9609-a261488d3c50.PNG)

**Comment by timbiles** [comment]
@pandeypiyush94 Thanks for letting me know! This issue should be corrected. The `appearance` property will display an empty array for those characters that do not appear in `Breaking Bad` but do appear in `Better Call Saul`
