### ISSUE TITLE
wrong data : Lydia Rodarte-Quayle status is not "Alive"

### ISSUE THREAD

**Issue by shambu2k** [timbiles/Breaking-Bad--API#48]
Walter clearly poisoned her with Ricin. Even though there was no confirmation of her death at the time when the final episode was released, shortly after El-Camino, Laura Fraser (the actress who played Lydia) herself confirmed her death in an [interview](https://www.digitalspy.com/tv/ustv/a29499912/breaking-bad-lydia-rodarte-quayle-el-camino-dead-laura-fraser/)

**Comment by timbiles** [comment]
Good catch. I'll make that update.
