### ISSUE TITLE
Henry Schrader has name Hank Schrader when looking up deaths

### ISSUE THREAD

**Issue by xylophonehero** [timbiles/Breaking-Bad--API#54]
When looking up character 5 in all characters, name of character is "Henry Schrader" but his associated death he has name "Hank Schrader". Probably should be the same so you can find the death info of a character that has died by looking them up by their name.

**Comment by timbiles** [comment]
@xylophonehero You should be to get the death count/info by using either name, `Hank Schrader` or `Henry Schrader`.

Both of these endpoints should return the same information.
https://www.breakingbadapi.com/api/death-count?name=hank+schrader
https://www.breakingbadapi.com/api/death-count?name=henry+schrader

**Comment by xylophonehero** [comment]
Hey that's true you can get the death-count from either name.

I have been playing with a Next.js app which is a BB Quiz on whether the characters are dead by the end of the series https://breaking-bad-quiz-five.vercel.app/

The way I currently get the death info of the characters is by loading all the death info from the /api/deaths endpoint and looking up the character by their name from those results. It doesn't work with Hank Schrader though as his name on the /api/characters endpoint is Henry Schrader but his name on the death end point is Hank Schrader, which means I can't find his death info by name.

**Comment by timbiles** [comment]
I see the issue. I think the easiest way would be the provide an endpoint to grab the death information by name, instead of grabbing all the deaths and then searching. I'll add that and let you know.

**Comment by timbiles** [comment]
@xylophonehero 

https://github.com/timbiles/Breaking-Bad--API/pull/55

Checkout this pull request. You should be able to grab an individuals death information now. Be aware, You would have to search for `Henry Schrader` for that death information, since that is the name associated with the character.

**Comment by xylophonehero** [comment]
Looks awesome!

I'll modify my quiz to use the new endpoint and let you know if it can find the death info for all the characters this way.

Thanks very much!
