### ISSUE TITLE
Outdated information in the API

### ISSUE THREAD

**Issue by ellenripley4** [timbiles/Breaking-Bad--API#8]
I noticed this when I was doing my app as part of my front-end development training. I noticed that Hank's murder counter is 0, although he at least (attention, spoiler!) killed Tuco. This page has more relevant information: https://breakingbad.fandom.com/wiki/List_of_killings_by_main_characters.

I can help you compile the data in any way you want to add to your database. I really like your API.

**Comment by timbiles** [comment]
@ellenripley4 Thanks for bring this to my attention! I'll look into this issue and get it corrected as soon as I can.

**Comment by timbiles** [comment]
@ellenripley4 you should find the correct information is provided with the following url. His death count returns 2 (I won't spoil who the second one is 😄).

`https://www.breakingbadapi.com/api/death-count?name=hank+schrader`

https://github.com/timbiles/Breaking-Bad--API/pull/10

**Comment by ellenripley4** [comment]
Sorry, but problem still here :) Here's why:

My app is working like that:
1. I recieve all charachters by https://www.breakingbadapi.com/api/characters/
2. Get all Names with field "name"
3. I recieve Henry Schrader (because that's how his name is stored) and his death count is 0 (https://www.breakingbadapi.com/api/death-count?name=henry+schrader)

**Comment by ellenripley4** [comment]
Sorry, but problem still here :) Here's why:I want to recieve death count of a selected character. My app is working like that:I recieve all charachters by https://www.breakingbadapi.com/api/characters/Get all Names with field "name"I recieve Henry Schrader (because that's how his name is stored) and his death count is 0 (https://www.breakingbadapi.com/api/death-count?name=henry+schrader)I doubled this message in GitHub since you closed the issue :)12.03.2020, 01:32, "Tim Biles" <notifications@github.com>:
@ellenripley4 you should find the correct information is provided with the following url. His death count returns 2 (I won't spoil who the second one is 😄).
https://www.breakingbadapi.com/api/death-count?name=hank+schrader
#10

**Comment by timbiles** [comment]
Ah, I see the dilemma. I can make that change this afternoon. Thanks again for bringing this to my attention!

**Comment by ellenripley4** [comment]
Thank you for your fast response and for building this API :)12.03.2020, 17:04, "Tim Biles" <notifications@github.com>:
Ah, I see the dilemma. I can make that change this afternoon. Thanks again for bringing this to my attention!
